sonar.organization=jbcom
sonar.projectKey=jbcom_jeep-sqlite-current-sqljs
sonar.projectName=jeep-sqlite-current-sqljs
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,www/**,loader/**,docs/**,src/index*.html,src/components.d.ts,src/assets/**
